from datetime import datetime
td=datetime.now()
print("today date:",td)
print("weekday in short version:",td.strftime("%a"))
print("weekday in ful version",td.strftime("%A"))
print("weekday as a number 0-6:",td.strftime("%w"))
print("Day of the month in num:",td.strftime("%d"))
print("Day of the month Name short-format:",td.strftime("%b"))
print("Day of the month name full version:",td.strftime("B"))
print("Month number:",td.strftime("%m"))
print("Year short version (without century):",td.strftime("%y"))
print("Day number of year :",td.strftime("%j"))
print("Week number of year(sunday as the first day of the week):",td.strftime("%U"))
print("Week number of year(monday as the first day of the week):",td.strftime("%W"))
print("Local version of date and time=",td.strftime("%c"))
print("Century	=",td.strftime("%C"))
print("Local version of date=",td.strftime("%x"))
print("Local version of time=",td.strftime("%X"))